# Generated by Django 5.0.4 on 2024-05-03 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_uploadimage_usermodel_images_usermodel_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='images',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.uploadimage'),
        ),
    ]
